import { images } from ".";

export const categories = [
  { name: "All", slug: "all" },
  { name: "Restaurant", slug: "restaurant" },
  { name: "Local", slug: "local" },
  { name: "Fine Dinner", slug: "fine-dinner" },
  { name: "Fast Food", slug: "fast-food" },
  { name: "Coffee & Tea", slug: "coffee-tea" },
  { name: "Bakery", slug: "bakery" },
  { name: "Breakfast", slug: "breakfast" },
  { name: "Lunch", slug: "lunch" },
  { name: "Dinner", slug: "dinner" },
  { name: "Drinks", slug: "drinks" },
  { name: "Snacks", slug: "snacks" },
  { name: "Healthy", slug: "healthy" },
  { name: "Seafood", slug: "seafood" },
  { name: "Desserts", slug: "desserts" },
  { name: "Pizza", slug: "pizza" },
  { name: "Burgers", slug: "burgers" },
  { name: "Chicken", slug: "chicken" },
  { name: "African Dishes", slug: "african" },
  { name: "Chinese", slug: "chinese" },
  { name: "Italian", slug: "italian" },
  { name: "Indian", slug: "indian" },
  { name: "Mexican", slug: "mexican" },
  { name: "Vegan", slug: "vegan" },
  { name: "Grill / BBQ", slug: "grill" },
];
export const exploreResturants = [
  {
    name: "Mr Bolat Pizza",
    slug: "mr-bolat-pizza",
    image: images.exploreRestaurantTwo,
  },
  {
    name: "Mamy's Dishes",
    slug: "mamys-dishes",
    image: images.exploreRestaurantOne,
  },
  {
    name: "Coco Cuisine",
    slug: "coco-cuisine",
    image: images.exploreRestaurantFive,
  },
  {
    name: "Abacha Cuisine",
    slug: "abacha-cuisine",
    image: images.exploreRestaurantThree,
  },
  {
    name: "Esther's Kitchen",
    slug: "esthers-kitchen",
    image: images.exploreRestaurantFour,
  },
];
export const popularMeals = [
  {
    name: "Fish and Chips",
    route: "/",
    price: 100,
    time: "20-30 mins",
    rating: 5,
    image: images.homeRecipeOne,
    id: 1,
  },
  {
    name: "Roasted chicken",
    route: "/",
    price: 100,
    time: "20-30 mins",
    rating: 5,
    image: images.homeRecipeTwo,
    id: 2,
  },
  {
    name: "Fish and Chips",
    route: "/",
    price: 100,
    time: "20-30 mins",
    rating: 5,
    image: images.homeRecipeOne,
    id: 1,
  },
  {
    name: "Roasted chicken",
    route: "/",
    price: 100,
    time: "20-30 mins",
    rating: 5,
    image: images.homeRecipeTwo,
    id: 2,
  },
  {
    name: "Fish and Chips",
    route: "/",
    price: 100,
    time: "20-30 mins",
    rating: 5,
    image: images.homeRecipeOne,
    id: 1,
  },
  {
    name: "Roasted chicken",
    route: "/",
    price: 100,
    time: "20-30 mins",
    rating: 5,
    image: images.homeRecipeTwo,
    id: 2,
  },
];
